const Data =[
    {
        id: 1,
        title: "Beetlejuice",
        year: "1988",
        runtime: "92",
        genres: "Comedy",
        director: "Tim Burton",
        actors: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
        plot: "A couple of recently deceased ghosts contract the services of a \"bio-exorcist\" in order to remove the obnoxious new owners of their house.",
        url:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/home-alone-1585876454.jpg"
    },
    {
        id: 2,
        title: "The Cotton Club",
        year: "1984",
        runtime: "127",
        genres:"Crime",
        director: "Francis Ford Coppola",
        actors: "Richard Gere, Gregory Hines, Diane Lane, Lonette McKee",
        plot: "The Cotton Club was a famous night club in Harlem. The story follows the people that visited the club, those that ran it, and is peppered with the Jazz music that made it so famous.",
        url:"https://s.studiobinder.com/wp-content/uploads/2019/11/73-Best-Crime-Movies-Featured-StudioBinder-min.jpg"    },
    {
        id: 3,
        title: "The Shawshank Redemption",
        year: "1994",
        runtime: "142",
        genres:"Drama",
        director: "Frank Darabont",
        actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
        plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
url:"https://media.glamour.com/photos/5ec2e91dccfbc8c1a8fe8cbf/master/w_3000,h_2032,c_limit/MSDTITA_FE057.jpg"    },
    {
        id: 4,
        title: "Crocodile Dundee",
        year: "1986",
        runtime: "97",
        genres:"Comedy",
        director: "Peter Faiman",
        actors: "Paul Hogan, Linda Kozlowski, John Meillon, DaidGulpilil",
        plot: "An American reporter goes to the Australian outback to meet an eccentric crocodile poacher and invites him to New York City.",
url:"https://www.themanual.com/wp-content/uploads/sites/9/2021/12/4ldpbxicygkkr8fghgjklphrfuc.jpg?p=1"    },
    {
        id: 5,
        title: "Valkyrie",
        year: "2008",
        runtime: "121",
        genres:"Comedy",
        director: "Bryan Singer",
        actors: "Tom Cruise, Kenneth Branagh, Bill Nighy, Tom Wilkinson",
        plot: "A dramatization of the 20 July assassination and political coup plot by desperate renegade German Army officers against Hitler during World War II.",
url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5s3huO34ZDLX3S6ArPDS4H9VNdWb8R3U11Kp1ooiRrPUo445mBDYhKPKvtzWX_OfzdSM&usqp=CAU"    },
    {
        id: 6,
        title: "Ratatouille",
        year: "2007",
        runtime: "111",
        genres:"action",
        director: "Brad Bird, Jan Pinkava",
        actors: "Patton Oswalt, Ian Holm, Lou Romano, Brian Dennehy",
        plot: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant.",
url:"https://m.media-amazon.com/images/M/MV5BOTdkNGY5YjItOWU5OC00NTA0LTkxMGEtZDRlNWZmMmI2ZGZmXkEyXkFqcGdeQXVyODIwMDI1NjM@._V1_.jpg"    },
    {
        id: 7,
        title: "City of God",
        year: "2002",
        runtime: "130",
        genres:"action",
        director: "Fernando Meirelles, Kátia Lund",
        actors: "Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen, Douglas Silva",
        plot: "Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths: one becomes a photographer, the other a drug dealer.",
url:"https://wwwimage-us.pplusstatic.com/thumbnails/photos/w370-q80/movie_asset/87/18/37/wom_salone_poster_1400x2100.jpg"    },
    {
        id: 8,
        title: "Memento",
        year: "2000",
        runtime: "113",
        genres:"action",
        director: "Christopher Nolan",
        actors: "Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junior",
        plot: "A man juggles searching for his wife's murderer and keeping his short-term memory loss from being an obstacle.",
url:"https://assets.vogue.in/photos/5f16b3bc9ffca08d1848369b/2:3/w_2560%2Cc_limit/must-watch%2520action%2520movies.jpg"    },
    {
        id: 9,
        title: "The Intouchables",
        year: "2011",
        runtime: "112",
        genres:"Comedy",
        director: "Olivier Nakache, Eric Toledano",
        actors: "François Cluzet, Omar Sy, Anne Le Ny, Audrey Fleurot",
        plot: "After he becomes a quadriplegic from a paragidng acidnt, an aristocrat hires a young man from the projects to be his caregiver.",
url:"https://cdn.feedingtrends.com/article-images/hollywood_comedy_movies_0e56fb9bf1.jpg"    },
    {
        id: 10,
        title: "Stardust",
        year: "2007",
        runtime: "127",
        genres: "action",
        director: "Matthew Vaughn",
        actors: "Ian McKellen, Bimbo Hart, Alastair MacIntosh, DaidKelly",
        plot: "In a countryid town bordering on a magical land, a young man makes a promise to his beloved that he'll retrieve a fallen star by venturing into the magical realm.",
url:"https://images2.minutemediacdn.com/image/upload/c_fill,w_720,ar_16:9,f_auto,q_auto,g_auto/shape/cover/sport/646987-jasin-boland-c-2012-warner-bros-entertainment-inc-54e2f8c553776eafbfd8ede11121a700.jpg"    },
    {
        id: 11,
        title: "Apocalypto",
        year: "2006",
        runtime: "139",
        genres:"Action",
        director: "Mel Gibson",
        actors: "Rudy Youngblood, Dalia Hernández, Jonathan Brewer, Morris Birdyellowhead",
        plot: "As the Mayan kingdom faces its decline, the rulers insist the key to prosperity is to build more temples and offer human sacrifices. Jaguar Paw, a young man captured for sacrifice, flees to avidhis fate.",
url:"https://www.hopestandard.com/wp-content/uploads/2018/07/12720668_web1_SKYSCRAPER_Movie_01.jpg"    },
    {
        id: 12,
        title: "Taxi Driver",
        year: "1976",
        runtime: "113",
        genres:"Crime",
        director: "Martin Scorsese",
        actors: "Diahnne Abbott, Frank Adu, Victor Argo, Gino Ardito",
        plot: "A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feeds his urge for violent action, attempting to save a preadolescent prostitute in the process.",
url:"https://img.mensxp.com/media/content/2017/Dec/the-top-10-crime-thriller-movies-of-20171400-1513772701.jpg"    },
    {
        id: 13,
        title: "No Country for Old Men",
        year: "2007",
        runtime: "122",
        genres:"Drama",
        director: "Ethan Coen, Joel Coen",
        actors: "Tommy Lee Jones, Javier Bardem, Josh Brolin, Woody Harrelson",
        plot: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
url:"https://goodmovieslist.com/best-movies/movie-posters/tt0111161.jpg"    },
    {
        id: 14,
        title: "Planet 51",
        year: "2009",
        runtime: "91",
        genres:"Animation",
        director: "Jorge Blanco, Javier Abad, Marcos Martínez",
        actors: "Jessica Biel, John Cleese, Gary Oldman, Dwayne Johnson",
        plot: "An alien civilization is invaded by Astronaut Chuck Baker, who believes that the planet was uninhabited. Wanted by the military, Baker must get back to his ship before it goes into orbit without him.",
url:"https://hips.hearstapps.com/hmg-prod/images/best-animated-movies-05-encanto-1669748585.jpeg?resize=480:*"    },
    {
        id: 15,
        title: "Looper",
        year: "2012",
        runtime: "119",
        genres:"Action",
        director: "Rian Johnson",
        actors: "Joseph Gordon-Levitt, Bruce Willis, Emily Blunt, Paul Dano",
        plot: "In 2074, when the mob wants to get idof someone, the target is sent into the past, where a hired gun awaits - someone like Joe - who one day learns the mob wants to 'close the loop' by sending back Joe's future self for assassination.",
url:"https://assets3.thrillist.com/v1/image/2803089/1200x600/scale;"    },
    {
        id: 16,
        title: "Corpse Bid",
        year: "2005",
        runtime: "77",
        genres: "Animation",
        director: "Tim Burton, Mike Johnson",
        actors: "Johnny Depp, Helena Bonham Carter, Emily Watson, Tracey Ullman",
        plot: "When a shy groom practices his wedding vows in the inadvertent presence of a deceased young woman, she rises from the grave assuming he has married her.",
url:"https://m.media-amazon.com/images/M/MV5BMTcyOTc2OTA1Ml5BMl5BanBnXkFtZTcwOTI1MjkzOQ@@._V1_FMjpg_UX1000_.jpg"    },
    {
        id: 17,
        title: "The Third Man",
        year: "1949",
        runtime: "93",
        genres:"Animation",
        director: "Carol Reed",
        actors: "Joseph Cotten, Aid Valli, Orson Welles, Trevor Howard",
        plot: "Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime.",
        posterUrl: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwNzMzMTQ0Ml5BMl5BanBnXkFtZTgwNjExMzUwNjE@._V1_SX300.jpg"
    },
    {
        id: 18,
        title: "The Beach",
        year: "2000",
        runtime: "119",
        genres:"Animation",
        director: "Danny Boyle",
        actors: "Leonardo DiCaprio, Daniel York, Patcharawan Patarakijjanon, Virginie Ledoyen",
        plot: "Twenty-something Richard travels to Thailand and finds himself in possession of a strange map. Rumours state that it leads to a solitary beach paradise, a tropical bliss - excited and intrigued, he sets out to find it.",
url:"https://www.rd.com/wp-content/uploads/2019/09/shutterstock_editorial_5884766b-e1569251332374.jpg"    },
    {
        id: 19,
        title: "Scarface",
        year: "1983",
        runtime: "170",
        genres:"Crime",
        director: "Brian De Palma",
        actors: "Al Pacino, Steven Bauer, Michelle Pfeiffer, Mary Elizabeth Mastrantonio",
        plot: "In Miami in 1980, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.",
url:"https://hips.hearstapps.com/hmg-prod/images/best-animated-movies-02-the-sea-beast-1669748043.jpeg?resize=480:*"    },
    {
        id: 20,
        title: "idand Nancy",
        year: "1986",
        runtime: "112",
        genres:"Animation",
        director: "Alex Cox",
        actors: "Gary Oldman, Chloe Webb, DaidHayman, Debby Bishop",
        plot: "Moridbiographical story of idVicious, bassist with British punk group the Sex Pistols, and his girlfriend Nancy Spungen. When the Sex Pistols break up after their fateful US tour, ...",
url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkDCpT_2u-m0PeIUYLY4oV3qY9gJKn8zJJNg&usqp=CAU"    }]

export default Data